apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: target-commercial-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-server
        image: nginx:latest # Using standard nginx as a placeholder until your CI pipeline pushes your custom image
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: target-commercial-prod
spec:
  type: LoadBalancer # This tells AWS to spin up a physical Elastic Load Balancer (ELB)
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
